label A_Favor_Promised :

    scene mint AFP 00
    scene mint AFP 01
    scene mint AFP 02
    scene mint AFP 03
    scene mint AFP 04
    scene mint AFP 05
    scene mint AFP 06
    scene mint AFP 07
    scene mint AFP 08
    scene mint AFP 09
    scene mint AFP 10
    scene mint AFP 11
    scene mint AFP 12
    scene mint AFP 13
    scene mint AFP 14
    scene mint AFP 15
    scene mint AFP 16
    scene mint AFP 17
    scene mint AFP 18
    scene mint AFP 19
    scene mint AFP 20
    scene mint AFP 21
    scene mint AFP 22
    scene mint AFP 23
    scene mint AFP 24
    scene mint AFP 25
    scene mint AFP 26
    scene mint AFP 27
    scene mint AFP 28
    scene mint AFP 29
    scene mint AFP 30
    scene mint AFP 31
    scene mint AFP 32
    scene mint AFP 33
    scene mint AFP 34
    scene mint AFP 35
    scene mint AFP 36
    scene mint AFP 37
    scene mint AFP 38
    scene mint AFP 39